apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs-dynamic-provisioner
parameters:
  archiveOnDelete: "false"
reclaimPolicy: Retain
