kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc-delete
spec:
  storageClassName: leighton-nfs-delete
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi